gallery/urls.py
from django.urls import path
from .views import *

app_name = "gallery"

urlpatterns = [
    path("", Albums.as_view(), name="albums"),
    path("search/", PictureSearch.as_view(), name="search"),
    path("tags/<str:tag_name>/", PicturesByTags.as_view(), name="tag_name"),
    # all albums
    path("albums/", Albums.as_view(), name="albums"),
    # add new album
    path("albums/add/", AlbumCreate.as_view(), name="create_album"),
    # pictures by album
    path("albums/<str:album_name>/", PicturesByAlbum.as_view(), name="single_album"),
    # upload pictures to album album_name
    path(
        "albums/<str:album_name>/upload/",
        PictureUpload.as_view(),
        name="upload_pictures",
    ),
    # delete album album_name
    path("albums/<str:album_name>/delete/", AlbumDelete.as_view(), name="delete_album"),
    # update name of the album album_name
    path("albums/<str:album_name>/update/", AlbumUpdate.as_view(), name="update_album"),
    # single picture
    path(
        "albums/<str:album_name>/<int:pk>/",
        PictureDetails.as_view(),
        name="single_picture",
    ),
    # delete single picture
    path(
        "albums/<str:album_name>/<int:pk>/delete/",
        PictureDelete.as_view(),
        name="delete_picture",
    ),
    # update single picture
    path(
        "albums/<str:album_name>/<int:pk>/update/",
        PictureUpdate.as_view(),
        name="update_picture",
    ),
]

gallery/models.py
import random
import shutil # for filesystem cleanup
from os.path import isdir # to check if directory exists
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=100, unique=True)
    creation_date = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = "Albums"
        ordering = ("-creation_date",)

    def item_count(self):
        n = Picture.objects.filter(album__name=self.name).count()
        if n > 1:
            return f"{n} items."
        elif n == 1:
            return "1 item."
        return "Empty album."

    def random_image(self):
        lst = Picture.objects.filter(album__name=self.name)
        if lst:
            return random.choice(lst).picture
        return None

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("gallery:single_album", kwargs={"album_name": self.name})

    def delete(self, *args, **kwargs):
        """Custom delete method to remove album directory once the album no longer exists in db"""
        
        location = settings.MEDIA_ROOT + "/" + self.name # location of album in the filesystem
        if isdir(location):
            shutil.rmtree(location)
        super().delete(*args, **kwargs)


def album_name(instance, filename):
    """Callable for upload_to argument in picture attribute below"""
    return f"{instance.album.name}/{filename}"


class Picture(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name="pictures")
    picture = models.ImageField(upload_to=album_name, default="blank/no_img.png")
    description = models.CharField(max_length=500, default="Empty")

    # tags mechanism
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "gallery:single_picture",
            kwargs={"album_name": self.album.name, "pk": self.pk},
        )

    def delete(self, *args, **kwargs):
        """Custom delete method to remove pictures references not only from db, 
        but also from the filesystem"""

        self.picture.delete()
        super().delete(*args, **kwargs)

gallery/forms.py
from django import forms
from .models import Album, Picture


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ("name",)
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "required": True,
                    "placeholder": "Album's name...",
                }
            )
        }


class UploadPictureForm(forms.Form):
    album = forms.ModelChoiceField(
        queryset=Album.objects, empty_label="Select album", label="Album"
    )
    picture = forms.ImageField(
        label="Pictures",
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
        required=False,
    )


class UpdatePictureForm(forms.Form):
    album = forms.ModelChoiceField(
        queryset=Album.objects, empty_label="Select album", label="Album"
    )
    picture = forms.ImageField(label="Picture")
    description = forms.CharField(label="Description", widget=forms.Textarea(attrs={}))
    tags = forms.CharField(label="Tags")

gallery/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.db.models import Q  # complex lookups (for searching)
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from django.views.generic.list import ListView
from .models import Album, Picture
from .forms import UploadPictureForm, UpdatePictureForm, AlbumForm

# Create your views here.

## Albums
class Albums(ListView):
    model = Album
    template_name = "gallery/index.html"
    context_object_name = "albums"
    paginate_by = 12


class AlbumCreate(LoginRequiredMixin, CreateView):
    model = Album
    form_class = AlbumForm

    # To conveniently swap 'Update' and 'Create' in album form
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update"] = False
        return context


class AlbumDelete(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy("gallery:albums")

    """
    To overcome error:
    'Generic detail view AlbumDelete must be called with either an object pk
     or a slug in the URLconf.'
    """

    def get_object(self):
        return get_object_or_404(Album, name=self.kwargs.get("album_name"))


class AlbumUpdate(LoginRequiredMixin, UpdateView):
    model = Album
    form_class = AlbumForm

    def get_object(self):
        return get_object_or_404(Album, name=self.kwargs.get("album_name"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update"] = True
        return context


## Pictures
class PictureUpload(LoginRequiredMixin, View):
    form_class = UploadPictureForm
    template_name = "gallery/upload_pictures_form.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    # override post method to upload multiple images
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            for file in form.files.getlist("picture"):
                Picture(
                    album=form.cleaned_data["album"],
                    picture=file,
                    description="Empty description",
                ).save()
            return redirect(
                "gallery:single_album", album_name=self.kwargs.get("album_name")
            )

        return render(request, self.template_name, {"form": form})


class PictureUpdate(LoginRequiredMixin, FormView):
    form_class = UpdatePictureForm
    template_name = "gallery/update_picture_form.html"
    success_url = reverse_lazy("gallery:albums")

    # def get_form(self, form_class):
    #     """
    #     Show the form populated with details from database, let user change them.
    #     """
    #     if form_class is None:
    #         form_class = self.get_form_class()
    #     picture = get_object_or_404(Picture, pk=self.kwargs['pk'])
    #     if picture:
    #         return form_class(instance=picture, **self.get_form_kwargs())
    #     else:
    #         return form_class(**self.get_form_kwargs())

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        file = request.FILES.get("picture")

        if form.is_valid():
            pic = get_object_or_404(Picture, pk=self.kwargs["pk"])
            pic.album = form.cleaned_data["album"]
            pic.picture = file
            pic.description = form.cleaned_data["description"]
            pic.tags = form.cleaned_data["tags"]
            pic.save()
            return redirect(
                "gallery:single_album", album_name=self.kwargs.get("album_name")
            )

        return render(request, self.template_name, {"form": form})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album_name"] = self.kwargs["album_name"]
        pk = self.kwargs["pk"]
        context["pk"] = pk
        context["picture"] = get_object_or_404(Picture, pk=pk)
        return context


class PictureSearch(ListView):
    model = Picture
    context_object_name = "pictures"
    template_name = "gallery/search_pictures.html"
    paginate_by = 50
    ordering = ("-published_date",)

    def get_queryset(self):
        search_query = self.request.GET.get("q", None)
        results = []
        if search_query:
            results = Picture.objects.filter(
                Q(album__name__icontains=search_query)
                | Q(description__icontains=search_query)
            ).distinct()
        return results


class PicturesByAlbum(ListView):
    context_object_name = "pictures"
    template_name = "gallery/pictures_by_album.html"
    paginate_by = 50
    ordering = ("-published_date",)

    def get_queryset(self):
        album = get_object_or_404(Album, name=self.kwargs["album_name"])
        results = []
        if album:
            results = Picture.objects.filter(album__name=album)
        return results

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album_name"] = self.kwargs.get("album_name", None)
        # to be implemented
        context["created"] = 0
        return context


class PicturesByTags(ListView):
    model = Picture
    context_object_name = "pictures"
    template_name = "gallery/pictures_by_tags.html"
    paginate_by = 50
    ordering = ("-published_date",)

    def get_queryset(self):
        tag = self.kwargs.get("tag_name", None)
        results = []
        if tag:
            results = Picture.objects.filter(tags__name=tag)
        return results


class PictureDetails(DetailView):
    model = Picture
    template_name = "gallery/single_picture.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album_name"] = self.kwargs.get("album_name", None)
        context["pk"] = self.kwargs.get("pk", None)
        return context


class PictureDelete(LoginRequiredMixin, DeleteView):
    model = Picture
    success_url = reverse_lazy("gallery:albums")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album_name"] = self.kwargs.get("album_name", None)
        context["pk"] = self.kwargs.get("pk", None)
        return context

gallery/templates/gallery/album_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Delete Album "{{ object }}" {% endblock %}

{% block subpage %} Delete Album "{{ object }}" {% endblock %}


{% block content %}
<div class="submission-form">
    <h3 class="my-4">Delete Album </h3>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete album "{{ object }}" with its content?</p>
        <button class="btn btn-primary" type="submit">Confirm</button>
    </form>
</div>
{% endblock %}

gallery/templates/gallery/album_form.html
{% extends 'base.html' %}

{% block title %} 
	{% if update %} Update {% else %} Create {% endif %} Album 
{% endblock %}

{% block subpage %}
	{% if update %} Update {% else %} Create {% endif %} Album 
{% endblock %}

{% block user_panel %} {% endblock %}

{% block content %}
<div class="submission-form">
	<h3 class="my-4">{% if update %} Update {% else %} Create {% endif %} Album</h3>
	<form method="post" action="">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <button class="btn btn-primary" type="submit">Submit</button>
	</form>
</div>
{% endblock %}

gallery/templates/gallery/index.html
{% extends 'base.html' %}

{% block title %} All albums {% endblock %}

{% block subpage %} {% endblock %}

{% block user_panel %}
    {% if user.is_authenticated %}
        <div class="my-3">
            <a href="{% url 'gallery:create_album' %}"><strong>New Album &nbsp;</strong><i class="fas fa-plus"></i></a>
        </div>
    {% else %}
        <!-- add some space -->
        <div class="my-3">&nbsp;</div>
    {% endif %}
{% endblock %}

{% block content %}
<!-- Photo Grid -->
<ul class="photo-grid list-unstyled mb-4">
    {% for album in albums %}
        <li>
            <a href="{% url 'gallery:single_album' album_name=album %}" class="text-dark">
                <div class="card rounded-0">
                    <img class="card-img-top rounded-0" src="{% if album.random_image.url %}{{ album.random_image.url }}{% else %}{{ MEDIA_PREFIX }}/media/placeholder.png{% endif %}">
                    <div class="card-body">
                        <p class="card-text"> {{ album.name }}, {{ album.item_count }} </p>
                    </div>
                </div>
            </a>
        </li>
    {% empty %}
        <p>No items to display.</p>
    {% endfor %}
</ul>

{% endblock %}

gallery/templates/gallery/picture_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Are you sure? {% endblock %}

{% block content %}
<div class="submission-form">
	<h3>Do you want to delete this picture?</h3>
		<a href="{% url 'gallery:single_picture' album_name=album_name pk=picture.pk %}">
			<img src="{{ picture.picture.url }}" style="width: 200px;">
		</a>
		<p>
			{{ picture.description }}
		</p>

		<form method="post">
		    {% csrf_token %}
		    {{ form.as_p }}
		    <button class="btn btn-primary" type="submit">Confirm</button>
		</form>
</div>
{% endblock %}

gallery/templates/gallery/picture_form.html
{% extends 'base.html' %}

{% block title %} 
    {% if update %} Update Picture {% else %} Upload Pictures {% endif %} 
{% endblock %}

{% block subpage %}
    {% if update %} Update Picture {% else %} Upload Pictures {% endif %} 
{% endblock %}

{% block user_panel %} {% endblock %}

{% block content %}
<div class="submission-form">
    <h3 class="my-4">{% if update %} Update Picture {% else %} Select pictures for album {{ album_name }} {% endif %}</h3>
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

gallery/templates/gallery/pictures_by_album.html
{% extends 'base.html' %}

{% block title %} Album: {{ album_name }} {% endblock %}

{% block subpage %} 
<a href="{% url 'gallery:single_album' album_name=album_name %}" class="nav-link">
    Album: {{ album_name }} <span class="sr-only">(current)</span> 
</a> 
{% endblock %}

{% block user_panel %}
    {% if user.is_authenticated %}
        <div class="my-3">
            <ul class="list-unstyled text-center">
                <li class="d-inline-block"><a href="{% url 'gallery:update_album' album_name=album_name %}" class="pl-3"><b>Update Album &nbsp;</b><i class="fas fa-edit"></i></a></li>
                <li class="d-inline-block"><a href="{% url 'gallery:delete_album' album_name=album_name %}" class="pl-3"><b>Delete Album &nbsp;</b><i class="fas fa-trash-alt"></i></a></li>
                <li class="d-inline-block"><a href="{% url 'gallery:upload_pictures' album_name=album_name %}" class="pl-3"><b>Upload Pictures &nbsp;</b><i class="fas fa-file-upload"></i></a></li>
            </ul>
        </div>
    {% else %}
        <!-- add some space -->
        <div class="my-3">&nbsp;</div>
    {% endif %}
{% endblock %}

{% block content %}

{% if pictures %}
<ul class="photo-grid list-unstyled mb-4">
    {% for picture in pictures %}
        <li>
            <div class="card rounded-0">
                <a href="{% url 'gallery:single_picture' album_name=picture.album.name pk=picture.pk %}" data-caption="{{ picture.description }}">
                    <img class="card-img-top rounded-0" src="{{ picture.picture.url }}">
                </a>
                {% if user.is_authenticated %}
                <div class="card-body">
                    <strong>Actions:&nbsp;</strong>
                    <a href="{% url 'gallery:update_picture' album_name=album_name pk=picture.pk %}" data-toggle="tooltip" title="Update picture"><i class="fas fa-edit"></i></a>
                    <a href="{% url 'gallery:delete_picture' album_name=album_name pk=picture.pk %}" data-toggle="tooltip" title="Delete picture"><i class="fas fa-trash-alt"></i></a>
                </div>
                {% endif %}
            </div>
        </li>
    {% endfor %}
</ul>
{% else %}
    <p>Empty album.</p>
{% endif %}

{% endblock %}

gallery/templates/gallery/pictures_by_tags.html
{% extends 'base.html' %}

{% block title %} Tag: ... {% endblock %}

{% block content %}
<h3> Pictures in ... </h3>
<hr>
<div class="d-flex justify-content-center flex-wrap">
{% for picture in pictures %}
    <div class="card picture-container ml-2">
        <img class="card-img" src="{{ picture.picture.url }}" alt="{{ picture.title }}">
        <div class="card-img-overlay">
            <a href="{% url 'gallery:single_picture' pk=picture.pk %}">
                <h4 class="card-title"><b>{{ picture.title }}</b></h4></a> by <a href="{% url 'gallery:author' author=picture.author.username %}"><em>{{ picture.author.first_name }}</em></a>
        </div>
    </div>
{% empty %}
    <p>No items to display.</p>
{% endfor %}
</div>
{% endblock %}

gallery/templates/gallery/search_pictures.html
{% extends 'base.html' %}

{% block title %} Search results for '{{ request.GET.q }}' {% endblock %}

{% block subpage %} 
	{% if request.GET.q %}
		Search results for "{{ request.GET.q }}"
	{% endif %}
{% endblock %}


{% block content %}
<div class="submission-form">
{% if request.GET.q %}
	{% for picture in pictures %}
	<div class="card picture-container ml-2">
		<img class="card-img" src="{{ picture.picture.url }}">
		<div class="card-img-overlay">
			<a href="{% url 'gallery:single_picture' album_name=picture.album.name pk=picture.pk %}">
		</div>
	</div>
	{% empty %}
		<p class="my-4">No pictures matching search query.</p>
	{% endfor %}
{% else %}
	<h3>Search</h3>
	<form method="GET" action="{% url 'gallery:search' %}">
	    <div class="input-group">
	        <input type="text" class="form-control" placeholder="Type your query here..." name="q">
	        <div class="input-group-append">
	            <button class="btn btn-outline-primary" type="button"><i class="fas fa-search"></i></button>
	        </div>
	    </div>
	</form>
{% endif %}
</div>
{% endblock %}

gallery/templates/gallery/single_picture.html
{% extends 'base.html' %}

{% block title %} {{ album_name }} {% endblock %}

{% block subpage %} 
<a href="{% url 'gallery:single_album' album_name=album_name %}" class="nav-link">
    Album: {{ album_name }} <span class="sr-only">(current)</span> 
</a> 
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center align-items-center my-2">
	<a href="#">&laquo;Previous</a> &nbsp;|&nbsp; <a href="#">Next&raquo;</a>
</div>

<div class="p-3">
	<img class="mb-2" src="{{ picture.picture.url }}" style="max-width: 100%; height: auto;">
	
	<p class="px-2">{{ picture.description }}</p>

	<div class="row my-2 px-2">
		<div class="col-9 text-left">
			<b>Tags:</b>&nbsp;
			{% for name in picture.tags.names %}
				{% if not forloop.first %}, {% endif %}
				<a href="{% url 'gallery:tag_name' tag_name=name %}">{{ name }}</a>
			{% endfor %}
		</div>
		{% if user.is_authenticated %}
		<div class="col-3 text-right">
			<a href="{% url 'gallery:update_picture' album_name=album_name pk=picture.pk %}" data-toggle="tooltip" title="Update picture"><i class="fas fa-edit"></i></a>
			<a href="{% url 'gallery:delete_picture' album_name=album_name pk=picture.pk %}" data-toggle="tooltip" title="Delete picture"><i class="fas fa-trash-alt"></i></a>
	    </div>
	    {% endif %}
	</div>

	<div class="fb-comments pr-3" data-href="{{ request.build_absolute_uri }}" data-numposts="3" width="100%"></div>
</div>
{% endblock %}

gallery/templates/gallery/update_picture_form.html
{% extends 'base.html' %}

{% block title %} 
    Update Picture
{% endblock %}

{% block subpage %}
    <a href="{% url 'gallery:update_picture' album_name=album_name pk=picture.pk %}" class="nav-link">
    Update Picture <span class="sr-only">(current)</span> 
	</a> 
{% endblock %}

{% block user_panel %} {% endblock %}

{% block content %}
<div class="submission-form">
    <h3 class="my-4">You are updating the following picture:</h3>
    <img src="{{ picture.picture.url }}" style="width: 200px;">
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

gallery/templates/gallery/upload_pictures_form.html
{% extends 'base.html' %}

{% block title %} 
    Upload Pictures
{% endblock %}

{% block subpage %}
    Upload Pictures
{% endblock %}

{% block user_panel %} {% endblock %}

{% block content %}
<div class="submission-form">
    <h3 class="my-4">Upload Pictures</h3>
    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
</div>
{% endblock %}