accounts/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, reverse_lazy
from .views import SignUp

app_name = "accounts"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy("accounts:password_change_done")
        ),
        name="password_change",
    ),
    path(
        "password_change_done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("accounts:password_reset_done")
        ),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("accounts:password_reset_complete")
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("signup/", SignUp.as_view(), name="signup"),
    # path('profile/', UpdateProfile.as_view(), name='profile'),
]

gallery/urls.py
from django.urls import path
from .views import *

app_name = "gallery"

urlpatterns = [
    path("", Albums.as_view(), name="albums"),
    path("search/", PictureSearch.as_view(), name="search"),
    path("tags/<str:tag_name>/", PicturesByTags.as_view(), name="tag_name"),
    # all albums
    path("albums/", Albums.as_view(), name="albums"),
    # add new album
    path("albums/add/", AlbumCreate.as_view(), name="create_album"),
    # pictures by album
    path("albums/<str:album_name>/", PicturesByAlbum.as_view(), name="single_album"),
    # upload pictures to album album_name
    path(
        "albums/<str:album_name>/upload/",
        PictureUpload.as_view(),
        name="upload_pictures",
    ),
    # delete album album_name
    path("albums/<str:album_name>/delete/", AlbumDelete.as_view(), name="delete_album"),
    # update name of the album album_name
    path("albums/<str:album_name>/update/", AlbumUpdate.as_view(), name="update_album"),
    # single picture
    path(
        "albums/<str:album_name>/<int:pk>/",
        PictureDetails.as_view(),
        name="single_picture",
    ),
    # delete single picture
    path(
        "albums/<str:album_name>/<int:pk>/delete/",
        PictureDelete.as_view(),
        name="delete_picture",
    ),
    # update single picture
    path(
        "albums/<str:album_name>/<int:pk>/update/",
        PictureUpdate.as_view(),
        name="update_picture",
    ),
]

gallery/models.py
import random
import shutil # for filesystem cleanup
from os.path import isdir # to check if directory exists
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=100, unique=True)
    creation_date = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = "Albums"
        ordering = ("-creation_date",)

    def item_count(self):
        n = Picture.objects.filter(album__name=self.name).count()
        if n > 1:
            return f"{n} items."
        elif n == 1:
            return "1 item."
        return "Empty album."

    def random_image(self):
        lst = Picture.objects.filter(album__name=self.name)
        if lst:
            return random.choice(lst).picture
        return None

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("gallery:single_album", kwargs={"album_name": self.name})

    def delete(self, *args, **kwargs):
        """Custom delete method to remove album directory once the album no longer exists in db"""
        
        location = settings.MEDIA_ROOT + "/" + self.name # location of album in the filesystem
        if isdir(location):
            shutil.rmtree(location)
        super().delete(*args, **kwargs)


def album_name(instance, filename):
    """Callable for upload_to argument in picture attribute below"""
    return f"{instance.album.name}/{filename}"


class Picture(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name="pictures")
    picture = models.ImageField(upload_to=album_name, default="blank/no_img.png")
    description = models.CharField(max_length=500, default="Empty")

    # tags mechanism
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "gallery:single_picture",
            kwargs={"album_name": self.album.name, "pk": self.pk},
        )

    def delete(self, *args, **kwargs):
        """Custom delete method to remove pictures references not only from db, 
        but also from the filesystem"""

        self.picture.delete()
        super().delete(*args, **kwargs)

gallery/forms.py
from django import forms
from .models import Album, Picture


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ("name",)
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "required": True,
                    "placeholder": "Album's name...",
                }
            )
        }


class UploadPictureForm(forms.Form):
    album = forms.ModelChoiceField(
        queryset=Album.objects, empty_label="Select album", label="Album"
    )
    picture = forms.ImageField(
        label="Pictures",
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
        required=False,
    )


class UpdatePictureForm(forms.Form):
    album = forms.ModelChoiceField(
        queryset=Album.objects, empty_label="Select album", label="Album"
    )
    picture = forms.ImageField(label="Picture")
    description = forms.CharField(label="Description", widget=forms.Textarea(attrs={}))
    tags = forms.CharField(label="Tags")

gallery/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.db.models import Q  # complex lookups (for searching)
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from django.views.generic.list import ListView
from .models import Album, Picture
from .forms import UploadPictureForm, UpdatePictureForm, AlbumForm

# Create your views here.

## Albums
class Albums(ListView):
    model = Album
    template_name = "gallery/index.html"
    context_object_name = "albums"
    paginate_by = 12


class AlbumCreate(LoginRequiredMixin, CreateView):
    model = Album
    form_class = AlbumForm

    # To conveniently swap 'Update' and 'Create' in album form
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update"] = False
        return context


class AlbumDelete(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy("gallery:albums")

    """
    To overcome error:
    'Generic detail view AlbumDelete must be called with either an object pk
     or a slug in the URLconf.'
    """

    def get_object(self):
        return get_object_or_404(Album, name=self.kwargs.get("album_name"))


class AlbumUpdate(LoginRequiredMixin, UpdateView):
    model = Album
    form_class = AlbumForm

    def get_object(self):
        return get_object_or_404(Album, name=self.kwargs.get("album_name"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update"] = True
        return context


## Pictures
class PictureUpload(LoginRequiredMixin, View):
    form_class = UploadPictureForm
    template_name = "gallery/upload_pictures_form.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    # override post method to upload multiple images
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            for file in form.files.getlist("picture"):
                Picture(
                    album=form.cleaned_data["album"],
                    picture=file,
                    description="Empty description",
                ).save()
            return redirect(
                "gallery:single_album", album_name=self.kwargs.get("album_name")
            )

        return render(request, self.template_name, {"form": form})


class PictureUpdate(LoginRequiredMixin, FormView):
    form_class = UpdatePictureForm
    template_name = "gallery/update_picture_form.html"
    success_url = reverse_lazy("gallery:albums")

    # def get_form(self, form_class):
    #     """
    #     Show the form populated with details from database, let user change them.
    #     """
    #     if form_class is None:
    #         form_class = self.get_form_class()
    #     picture = get_object_or_404(Picture, pk=self.kwargs['pk'])
    #     if picture:
    #         return form_class(instance=picture, **self.get_form_kwargs())
    #     else:
    #         return form_class(**self.get_form_kwargs())

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        file = request.FILES.get("picture")

        if form.is_valid():
            pic = get_object_or_404(Picture, pk=self.kwargs["pk"])
            pic.album = form.cleaned_data["album"]
            pic.picture = file
            pic.description = form.cleaned_data["description"]
            pic.tags = form.cleaned_data["tags"]
            pic.save()
            return redirect(
                "gallery:single_album", album_name=self.kwargs.get("album_name")
            )

        return render(request, self.template_name, {"form": form})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album_name"] = self.kwargs["album_name"]
        pk = self.kwargs["pk"]
        context["pk"] = pk
        context["picture"] = get_object_or_404(Picture, pk=pk)
        return context


class PictureSearch(ListView):
    model = Picture
    context_object_name = "pictures"
    template_name = "gallery/search_pictures.html"
    paginate_by = 50
    ordering = ("-published_date",)

    def get_queryset(self):
        search_query = self.request.GET.get("q", None)
        results = []
        if search_query:
            results = Picture.objects.filter(
                Q(album__name__icontains=search_query)
                | Q(description__icontains=search_query)
            ).distinct()
        return results


class PicturesByAlbum(ListView):
    context_object_name = "pictures"
    template_name = "gallery/pictures_by_album.html"
    paginate_by = 50
    ordering = ("-published_date",)

    def get_queryset(self):
        album = get_object_or_404(Album, name=self.kwargs["album_name"])
        results = []
        if album:
            results = Picture.objects.filter(album__name=album)
        return results

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album_name"] = self.kwargs.get("album_name", None)
        # to be implemented
        context["created"] = 0
        return context


class PicturesByTags(ListView):
    model = Picture
    context_object_name = "pictures"
    template_name = "gallery/pictures_by_tags.html"
    paginate_by = 50
    ordering = ("-published_date",)

    def get_queryset(self):
        tag = self.kwargs.get("tag_name", None)
        results = []
        if tag:
            results = Picture.objects.filter(tags__name=tag)
        return results


class PictureDetails(DetailView):
    model = Picture
    template_name = "gallery/single_picture.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album_name"] = self.kwargs.get("album_name", None)
        context["pk"] = self.kwargs.get("pk", None)
        return context


class PictureDelete(LoginRequiredMixin, DeleteView):
    model = Picture
    success_url = reverse_lazy("gallery:albums")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["album_name"] = self.kwargs.get("album_name", None)
        context["pk"] = self.kwargs.get("pk", None)
        return context

gallery/templates/base.html
{% load static %}
{% get_media_prefix as MEDIA_PREFIX %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Django Gallery">
    <meta name="author" content="Author">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans&display=swap" rel="stylesheet">

    <title>{% block title %} Gallery {% endblock %}</title>
</head>

<body>
    <!-- Facebook comments -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.1';
      fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<header>
    <div class="bg-dark">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <a class="navbar-brand" href="{% url 'gallery:albums' %}"><i class="fas fa-camera"></i> Django Gallery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                        {% block subpage %} {% endblock %}
                        </li>
                    </ul>
                    <form class="form-inline" method="GET" action="{% url 'gallery:search' %}">
                        <div class="input-group input-group-sm">
                            <input type="text" class="form-control" placeholder="Search..." name="q">
                            <div class="input-group-append">
                                <button class="btn btn-light active" type="button">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                    <ul class="navbar-nav ml-4">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            Logged as: <b>{{ user.username.capitalize }}</b> <i class="fas fa-user"></i>
                            |
                            <a href="{% url 'accounts:logout' %}?next={{ request.path | urlencode }}" class="text-light">Logout <i class="fas fa-sign-out-alt"></i></a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{% url 'accounts:login' %}?next={{ request.path | urlencode }}" class="text-light">Sign In <i class="fas fa-sign-in-alt"></i></a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</header>

<div class="container">
    {% block user_panel %} {% endblock %}

    {% block content %} {% endblock %}
</div>
<footer>
    <p class="text-dark">
        <a href="{% url 'feed' %}">Get notified about new albums by subscribing.</a>
    </p>

    <p class="m-0 text-center text-dark">
        Copyright &copy; {% now "Y" %} by Author<br>
        <a href="#">Back to top</a>
    </p>
</footer>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>